
project_id = "nvptlivnsclbinfaifoc"

[functions.generate-lovebug]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.verify-email-redirect]
verify_jwt = false
