// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvptlivnsclbinfaifoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52cHRsaXZuc2NsYmluZmFpZm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NDIxNDQsImV4cCI6MjA1NjExODE0NH0.zLPvbThviajXEZyQNP4Aag7B9liEfgw96ByZ2Wo7jU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);